name: Build Pipeline

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout du code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Installation des dépendances
      run: npm ci
    
    - name: Build du projet
      run: npm run build
    
    - name: Succès du build
      run: echo " Build terminé avec succès !"